=== abysslover/jsper_ajax/jspers_ajax/ch03/WebContent/xsd/HelloXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/HelloXSD" xmlns:tns="http://www.example.org/HelloXSD" elementFormDefault="qualified">

    <complexType name="PersonType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="address" type="tns:AddressType" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
        <attributeGroup ref="tns:PersonAttributeGroup"></attributeGroup>
    </complexType>

    <complexType name="AddressType">
    	<sequence>
    		<element name="nation" type="tns:SubAddressType"></element>
    		<element name="state" type="tns:SubAddressType"></element>
    		<element name="city" type="tns:SubAddressType"></element>
    		<element name="street" type="tns:SubAddressType"></element>
    	</sequence>
    </complexType>

    <complexType name="SubAddressType">
    	<sequence>
    		<element name="item" type="tns:ItemType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="ItemType">
        <attributeGroup ref="tns:ItemAttributeGroup"></attributeGroup>
    </complexType>

    <attributeGroup name="PersonAttributeGroup">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="age" type="string"></attribute>
    	<attribute name="birth" type="string"></attribute>
    </attributeGroup>

    <attributeGroup name="ItemAttributeGroup">
    	<attribute name="code" type="string"></attribute>
    	<attribute name="label" type="string"></attribute>
    </attributeGroup>

    <element name="person" type="tns:PersonType"></element>
</schema>

=== abysslover/jsper_ajax/jspers_ajax/ch03/WebContent/HelloXML2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:person age="26" birth="1982. 07. 02" name="임은천"
	xmlns:tns="http://www.example.org/HelloXSD"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/HelloXSD HelloXSD.xsd">
	<name>Magneto</name>
	<address>
		<nation>
			<item label="한국" code="1"></item>
			<item label="천국" code="2" />
		</nation>
		<state>
			<item label="전라남도" code="1" />
		</state>
		<city>
			<item label="순천시" code="1" />
		</city>
		<street>
			<item label="매곡동" code="1" />
		</street>
	</address>
</tns:person>
