=== abysslover/jsper_ajax/jspers_ajax/ch04/WebContent/xsd/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://javawide.com/menu" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:jwide="http://javawide.com/menu">
    <annotation>
    	<documentation>
    		이 XSD 파일은 javawide.com의 메뉴에 사용되는 XML Schema 파일입니다. 이 메뉴는 책을
    		구매한 사람만 사용할 수 있습니다. 무단 전제 및 복제를 금합니다. 책을 구매하지 않고 사용할 경우 제
    		홈페이지에 100번 이상 방문 해야 합니다. -_ -;;
    	</documentation>
    </annotation>

    <complexType name="MenuType">
    	<sequence>
    		<element name="menu" type="jwide:MenuType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
        <attributeGroup ref="jwide:MenuAttributes"></attributeGroup>
    </complexType>

    <element name="menus" type="jwide:MenuType"></element>

    <attributeGroup name="MenuAttributes">
    	<attribute name="title" type="string" use="required"></attribute>
    	<attribute name="href" type="anyURI" use="required"></attribute>
    	<attribute name="hovercolor" type="string"></attribute>
    	<attribute name="blurcolor" type="string"></attribute>
    </attributeGroup>
</schema>

=== abysslover/jsper_ajax/jspers_ajax/ch04/WebContent/menus.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xslt/menu.xsl" type="text/xsl" media="screen" ?>
<jwide:menus xmlns="http://javawide.com/menu"
	xmlns:jwide="http://javawide.com/menu"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://javawide.com/menu xsd/menu.xsd"
	title="root" href="#">
	<menu hovercolor="lightskyblue" blurcolor="white" href="http://javawide.com" title="자바 와이드" />
	<menu href="#friend" title="친구">
		<menu href="http://ikstyle.net" title="일가 홈페이지"></menu>
	</menu>
	<menu href="#searchEngine" title="검색 엔진">
		<menu href="http://www.naver.com" title="네이버"></menu>
		<menu href="http://www.google.com" title="구글"></menu>
	</menu>
	<menu href="#community" title="커뮤니티">
		<menu href="http://okjsp.pe.kr" title="okjsp"></menu>
		<menu href="http://taeyo.net" title="태요"></menu>
	</menu>
</jwide:menus>
